### PR TITLE
Safestart rewrite

### LINKED ISSUE #219: Safe Start doesn't work with UAVs (or just the MQ-12).
While trying to sort out disableUAVConnectability (and failing), with Safe Start placed and active, I entered the UAV gunner's view and accidentally fired off a Scalpel ATGM.

That was entirely unexpected, so issue posted.

### PR DESCRIPTION
**Pull request by Freddo3000**
Rewrites the safestart module to better handle JIPs, as well as add some other features.  
This is done by using a CBA PerFrameHandler object, rather than storing it inside of the safestart module.

### Added features:
* Ticking sound for final few seconds
* Readded dry fire sound
* Option for handling AI during safestart
* Option for default safestart duration on missions without module
* ACE compat for left click actions
* Preset trigger activating once safestart has ended
* Changed control type to sliderTime

### Controllable via CBA settings:
image

### Removed features:
* Per object/group/side safestart *via module* - Difficult to synchronize across JIPs and server. It can however be manually scripted using provided functions, with a custom JIP handler.

---
Should resolve #219

### CODE REVIEW

**Comment by headswe** [comment]
I just want to start off by saying what a great job you have been doing and I think your contributions are very valuable to TMF as a whole.

But once again I found myself with another PR from you where it feels like brevity and neat syntax is taken to a new extreme level just to satisfy some sort of "Less code, the better" strategy.
And I find that it makes for a very tedious review process for myself and I pity the person who has to tweak something in this in the future.

While the new CBA PerFrameHandler object is really neat, without the proper dress up, it is quite frankly a mess.

I also find that while the language (SQF) has many flaws, trying to hide the flaws by overusing Macros is not my preferred route.

For these reasons alone, I would not accept it.

Now, you have undoubtedly solved many of the issues that plagued the safe start but I find the removal of the module function, less than stellar.

Modules functions are for your average mission maker and give an easy way for non-technical users to grasp features and their setting, simply place down the module and configure, don't want it? delete it.

Thanks for reading. :)

**Comment by Freddo3000** [comment]
@headswe 
Re: 
> Now, you have undoubtedly solved many of the issues that plagued the safe start but I find the removal of the module function, less than stellar.  
> Modules functions are for your average mission maker and give an easy way for non-technical users to grasp features and their setting, simply place down the module and configure, don't want it? delete it.

The module is not removed, only the functionality for per side/group/object functionality, as it is difficult to get right with JIPs and server execution, where it is currently failing in my experience.

I'll look into further commenting and adding whitespace to the PFH function, in order to make it more understandable.

On the point of overuse of macros, which types of macros are you referring to? Is it logging, custom `#define` or stuff like `ADD(x,y)`?

**Comment by Freddo3000** [comment]
Tell me if that is sufficient, and if not what needs improvement.

**Comment by Freddo3000** [comment]
Tested locally hosted dedicated server, and it appears to work without issue for JIPs. Tested with AI slots both enabled and disabled. However one issue I notice is that the Safestart text does not display currently in the briefing screen.

**Pull request merged**
