### PR TITLE
Fix spectator JIP setting

### LINKED ISSUE #341: Players randomly kicked to spectator, JIP involvement
Message appeared on screen about players JIPing and being forced to spectator, despite the TMF add-on configuration about JIP being allowed even after safestart is over. In the course of about an hour it happened to three players who were doing nothing out of the ordinary.

No ACRE, MP respawn settings allowed Respawn on Custom Position and Select Respawn Position but also had the TMF Spectator box ticked (possibly part of the problem?).

Apologies for the rather vague report.

### PR DESCRIPTION
**Pull request by Freddo3000**
Appears that CBA settings don't have time to synchronise. Putting it behind a "CBA_settingsInitialized" eventhandler should solve it.

Fixes #341

### CODE REVIEW

**Comment by headswe** [comment]
Fixes a fixed bug?

**Comment by Freddo3000** [comment]
Mixed up the ticket. Anyhow, it appears that despite the setting being set to 1 (always allow) players are still getting kicked to spectator. I believe this is due to the settings not having enough time to be synchronized, so putting it behind the "CBA_settingsInitialized" event should fix that, or at least act as an additional safeguard.

**Comment by headswe** [comment]
Have you tested this in a dedicated enviroment?

**Comment by Freddo3000** [comment]
> 
> 
> Have you tested this in a dedicated enviroment?

I've tested it in a local dedicated environment

**Pull request merged**
