### PR TITLE
Use isNotEqualTo

### PR DESCRIPTION
**Pull request by Neviothr**

### CODE REVIEW

**Comment by Freddo3000** [comment]
Waiting on dev branch? https://community.bistudio.com/wiki/isNotEqualTo

**Comment by headswe** [comment]
Hunting for a t-shirt?

**Comment by Neviothr** [comment]
> Waiting on dev branch? https://community.bistudio.com/wiki/isNotEqualTo

Yep, added in 2.01.

**Comment by Neviothr** [comment]
> Hunting for a t-shirt?

See it how you want, they don't even ship here IIRC 🤷

**Pull request closed without merging**
