### PR TITLE
Changed map of the template to VR and moved units.

### PR DESCRIPTION
**Pull request by Freddo3000**
This change was made because on some smaller maps units were ending up outside the map area, and could therefore be bothersome to retrieve.

### CODE REVIEW

**Comment by Freddo3000** [comment]
May be worth mentioning that this is the first time I've used github, in case I've made any mistakes.

**Comment by Freddo3000** [comment]
as can be seen there.

**Comment by cptnnick** [comment]
According to git, no changes have been made to the mission.sqm, so the units haven't moved in this merge.

**Comment by Freddo3000** [comment]
Huh, I'll have a look again.

**Comment by Freddo3000** [comment]
Should be fixed

**Pull request closed without merging**
